---
all:
  children:
    proxmox_vms:
      children:
        debian_vms:
          children:
            lenmail_de_preseed:
              hosts:
                lb.lenmail.de:
                  ansible_host: lb.lenmail.de
                  proxmox_automatic_vmid: 4309
                llm.lenmail.de:
                  ansible_host: llm.lenmail.de
                  proxmox_automatic_vmid: 4313
                openclaw.lenmail.de:
                  ansible_host: openclaw.lenmail.de
                  proxmox_automatic_vmid: 4311
                opencode.lenmail.de:
                  ansible_host: opencode.lenmail.de
                  proxmox_automatic_vmid: 4312
                satisfactory.lenmail.de:
                  ansible_host: satisfactory.lenmail.de
                  proxmox_automatic_vmid: 4314
            swarm_preseed:
              hosts:
                swarm01.lenhardt-it.com:
                  ansible_host: swarm01.lenhardt-it.com
                  proxmox_automatic_vmid: 4321
                swarm02.lenhardt-it.com:
                  ansible_host: swarm02.lenhardt-it.com
                  proxmox_automatic_vmid: 4322
                swarm03.lenhardt-it.com:
                  ansible_host: swarm03.lenhardt-it.com
                  proxmox_automatic_vmid: 4323