---
proxmox_automatic_install_source: "cdrom"
proxmox_automatic_source_iso_path: "/srv/iso/debian-13.4.0-amd64-DVD-1.iso"
proxmox_automatic_networks:
  - name: net0
    bridge: vmbr1
    vlanid: 3
    ip: "192.0.2.17"
    netmask: "255.255.255.0"
    gateway: "192.0.2.1"
