---
all:
  children:
    proxmox_vms:
      children:
        rocky_vms:
          hosts:
            rocky01.example.com:
              ansible_host: rocky01.example.com
              proxmox_automatic_vmid: 3014
            rocky02.example.com:
              ansible_host: rocky02.example.com
              proxmox_automatic_vmid: 3016
        debian_vms:
          hosts:
            debian01.example.com:
              ansible_host: debian01.example.com
              proxmox_automatic_vmid: 3015
            debian02.example.com:
              ansible_host: debian02.example.com
              proxmox_automatic_vmid: 3017
